// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RuntimeLogCategory = ("DB" | "PERSISTENCE" | "REQUEST" | "WEB_SERVICE" | "MACRO" | "MAIL" | "PROCESS" | "WEB_SERVICE_PROCESS" | "CONTENT_MANAGEMENT" | "HTML" | "EVENT" | "USER" | "HTML_DIALOG" | "BUSINESS_DATA" | "REST_CLIENT" | "CASE_MAP")
export type Level = "OFF" | "FATAL" | "ERROR" | "WARN" | "INFO" | "DEBUG" | "TRACE" | "ALL";

export interface Logs {
  runtimeLogEntryLsp: RuntimeLogEntry[];
  void: Void;
  [k: string]: unknown;
}
export interface RuntimeLogEntry {
  category: RuntimeLogCategory;
  level: Level;
  message: string;
  processElement: string;
  project: string;
  request: string;
  throwableInformationMsg: string;
  timestamp: string;
  userDialogId: string;
  [k: string]: unknown;
}
export interface Void {
  [k: string]: unknown;
}
