packages:
  - webviews/*
  - playwright
  - extension

allowUnusedPatches: true
blockExoticSubdeps: true

ignoredBuiltDependencies:
  - '@swc/core'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@axonivy/*'

overrides:
  dompurify@>=3.1.3 <=3.3.1: '>=3.3.2'
  lodash@<=4.17.23: '>=4.18.0'

patchedDependencies:
  monaco-editor: patches/monaco-editor.patch

preferWorkspacePackages: true

publicHoistPattern:
  - eslint

sideEffectsCache: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # minutes (30 days)
