packages:
  - webviews/*
  - playwright
  - extension

ignoredBuiltDependencies:
  - '@swc/core'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar

onlyBuiltDependencies:
  - monaco-languageclient

preferWorkspacePackages: true

publicHoistPattern:
  - eslint

sideEffectsCache: false
