packages:
  - webviews/*
  - playwright
  - extension
allowUnusedPatches: true
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@axonivy/*'
  # Renovate security update: esbuild@0.28.1
  - esbuild@0.28.1
  - dompurify@3.4.11
overrides:
  dompurify: '>=3.4.11'
  lodash@<=4.17.23: '>=4.18.0'
  uuid@<14.0.0: '>=14.0.0'
patchedDependencies:
  monaco-editor: patches/monaco-editor.patch
preferWorkspacePackages: true
publicHoistPattern:
  - eslint
registries:
  '@axonivy': 'https://npmjs-registry.ivyteam.ch/'
sideEffectsCache: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # minutes (30 days)
allowBuilds:
  '@swc/core': false
  '@vscode/vsce-sign': false
  esbuild: false
  keytar: false
verifyDepsBeforeRun: warn
