packages:
  - webviews/*
  - playwright
  - extension

ignoredBuiltDependencies:
  - '@swc/core'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar

onlyBuiltDependencies:
  - monaco-languageclient

preferWorkspacePackages: true

publicHoistPattern:
  - eslint

sideEffectsCache: false

overrides:
  '@codingame/monaco-vscode-configuration-service-override': 24.2.0
  '@codingame/monaco-vscode-editor-service-override': 24.2.0
  '@codingame/monaco-vscode-api': 24.2.0
  '@codingame/monaco-vscode-editor-api': 24.2.0
  '@codingame/monaco-vscode-extensions-service-override': 24.2.0
  '@codingame/monaco-vscode-extension-api': 24.2.0
  '@codingame/monaco-vscode-languages-service-override': 24.2.0
  '@codingame/monaco-vscode-language-pack-cs': 24.2.0
  '@codingame/monaco-vscode-language-pack-de': 24.2.0
  '@codingame/monaco-vscode-language-pack-es': 24.2.0
  '@codingame/monaco-vscode-language-pack-fr': 24.2.0
  '@codingame/monaco-vscode-language-pack-it': 24.2.0
  '@codingame/monaco-vscode-language-pack-ja': 24.2.0
  '@codingame/monaco-vscode-language-pack-ko': 24.2.0
  '@codingame/monaco-vscode-language-pack-pl': 24.2.0
  '@codingame/monaco-vscode-language-pack-pt-br': 24.2.0
  '@codingame/monaco-vscode-language-pack-qps-ploc': 24.2.0
  '@codingame/monaco-vscode-language-pack-ru': 24.2.0
  '@codingame/monaco-vscode-language-pack-tr': 24.2.0
  '@codingame/monaco-vscode-language-pack-zh-hans': 24.2.0
  '@codingame/monaco-vscode-language-pack-zh-hant': 24.2.0
  '@codingame/monaco-vscode-localization-service-override': 24.2.0
  '@codingame/monaco-vscode-log-service-override': 24.2.0
  '@codingame/monaco-vscode-model-service-override': 24.2.0
  '@codingame/monaco-vscode-monarch-service-override': 24.2.0
  '@codingame/monaco-vscode-textmate-service-override': 24.2.0
  '@codingame/monaco-vscode-theme-defaults-default-extension': 24.2.0
  '@codingame/monaco-vscode-theme-service-override': 24.2.0
  '@codingame/monaco-vscode-views-service-override': 24.2.0
  '@codingame/monaco-vscode-workbench-service-override': 24.2.0
  '@codingame/monaco-vscode-standalone-languages': 24.2.0
  '@codingame/monaco-vscode-standalone-css-language-features': 24.2.0
  '@codingame/monaco-vscode-standalone-html-language-features': 24.2.0
  '@codingame/monaco-vscode-standalone-json-language-features': 24.2.0
  '@codingame/monaco-vscode-standalone-typescript-language-features': 24.2.0
  '@codingame/monaco-vscode-keybindings-service-override': 24.2.0
