#!/usr/bin/env node

const { exit } = require('process');
const fs = require('fs');
const tsGen = require('json-schema-to-typescript');
const http = require('https');

tsGen.DEFAULT_OPTIONS.bannerComment = `
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
`;

function loadJson(uri) {
  console.log(`loading ${uri}`);
  const download = new Promise(result =>
    http.get(uri, res => {
      res.setEncoding('utf8');
      let body = '';
      res.on('data', data => {
        body += data;
      });
      res.on('end', () => {
        body = JSON.parse(body);
        result(body);
      });
    })
  );
  return download;
}

async function generateSchema(schemaUri, tsOut, rootName) {
  const args = process.argv.slice(2);
  if (args.length > 0) {
    if (args[0] === 'clean') {
      console.log('cleaning ' + tsOut);
      if (fs.existsSync(tsOut)) {
        fs.unlinkSync(tsOut);
      }
      exit(0);
    }
    schemaUri = args[0];
  }

  if (schemaUri.startsWith('http')) {
    return loadJson(schemaUri).then(schema => tsGen.compile(schema, rootName));
  } else {
    return tsGen.compileFromFile(schemaUri);
  }
}

function writeSrc(ts, tsOut) {
  fs.writeFileSync(tsOut, ts);
  console.log(`generated ${tsOut}`);
}

module.exports = { generateSchema, writeSrc };
