// Generated by Copilot to reflect https://json-schema.axonivy.com/market/10.0.0/product.json
export interface MarketProduct {
  $schema?: string;
  installers: Installer[];
  minimumIvyVersion?: string;
}

export interface Installer {
  id: 'maven-dependency' | 'maven-import' | 'maven-dropins';
  data: MavenDependencyInstaller | MavenProjectInstaller | MavenDropinsInstaller;
}

export interface MavenDependencyInstaller {
  dependencies: Dependency[];
  repositories?: Repository[];
}

export interface MavenProjectInstaller {
  projects: Project[];
  repositories?: Repository[];
}

export interface MavenDropinsInstaller {
  dependencies: Dependency[];
  repositories?: Repository[];
}

export interface Dependency {
  artifactId: string;
  classifier?: string;
  exclusions?: Exclusion[];
  groupId: string;
  managementKey?: string;
  optional?: string;
  scope?: string;
  systemPath?: string;
  type?: string;
  version: string;
}

export interface Exclusion {
  artifactId: string;
  groupId: string;
}

export interface Project {
  artifactId: string;
  groupId: string;
  importInWorkspace?: boolean;
  type?: string;
  version: string;
}

export interface Repository {
  id: string;
  layout?: string;
  name?: string;
  releases?: RepositoryPolicy;
  snapshots?: RepositoryPolicy;
  url: string;
}

export interface RepositoryPolicy {
  checksumPolicy?: string;
  enabled?: string;
  updatePolicy?: string;
}
