/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `MarketProduct`'s JSON-Schema
 * via the `definition` "Installer".
 */
export type Installer = ({
[k: string]: unknown
} & {
id?: (("maven-import" | "maven-dependency") & string)
data: any |  {
[k: string]: unknown
}
})

export interface MarketProduct {
  $schema?: string;
  installers?: Installer[];
  /**
   * The minimal version of ivy that is required to run this product.
   */
  minimumIvyVersion?: string;
}
/**
 * This interface was referenced by `MarketProduct`'s JSON-Schema
 * via the `definition` "Dependency".
 */
export interface Dependency {
  artifactId?: string;
  classifier?: string;
  exclusions?: Exclusion[];
  groupId?: string;
  managementKey?: string;
  optional?: string;
  scope?: string;
  systemPath?: string;
  type?: string;
  version?: string;
}
/**
 * This interface was referenced by `MarketProduct`'s JSON-Schema
 * via the `definition` "Exclusion".
 */
export interface Exclusion {
  artifactId?: string;
  groupId?: string;
}
/**
 * This interface was referenced by `MarketProduct`'s JSON-Schema
 * via the `definition` "MavenDependencyInstaller".
 */
export interface MavenDependencyInstaller {
  /**
   * ivy projects as maven dependencies
   */
  dependencies?: Dependency[];
  /**
   * maven repositories where the projects are available
   */
  repositories?: Repository[];
}
/**
 * This interface was referenced by `MarketProduct`'s JSON-Schema
 * via the `definition` "Repository".
 */
export interface Repository {
  id?: string;
  layout?: string;
  name?: string;
  releases?: RepositoryPolicy;
  snapshots?: RepositoryPolicy;
  url?: string;
}
/**
 * This interface was referenced by `MarketProduct`'s JSON-Schema
 * via the `definition` "RepositoryPolicy".
 */
export interface RepositoryPolicy {
  checksumPolicy?: string;
  enabled?: string;
  updatePolicy?: string;
}
/**
 * This interface was referenced by `MarketProduct`'s JSON-Schema
 * via the `definition` "MavenProjectInstaller".
 */
export interface MavenProjectInstaller {
  /**
   * ivy projects as maven dependencies
   */
  projects: Project[];
  /**
   * maven repositories where the projects are available
   */
  repositories?: Repository[];
}
/**
 * This interface was referenced by `MarketProduct`'s JSON-Schema
 * via the `definition` "Project".
 */
export interface Project {
  /**
   * maven artifact id
   */
  artifactId?: string;
  /**
   * maven group id
   */
  groupId?: string;
  /**
   * wether project should be imported or not
   */
  importInWorkspace?: boolean;
  /**
   * maven type
   */
  type?: string;
  /**
   * maven version
   */
  version?: string;
}
