name: AI-build
on:
  schedule:
    - cron: '0 1 * * 0' # 1 AM on Sunday
  push:
    branches:
      - ai.*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5.1
        with:
          maven-version: 3.9.13
      - name: Build VSC
        run: |
          corepack enable
          pnpm install
          pnpm run build:production
          pnpm run package
      - name: Build with Maven
        run: |
          export HOST_UID="$(id -u)"
          export HOST_GID="$(id -g)"
          mvn clean verify -f aitest/pom.xml -ntp
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          TESTCONTAINERS_REUSE_ENABLE: 'false'
      - name: Archive test reports
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-reports
          retention-days: 5
          path: |
            ci-user-data/logs/**/*
            ci-user-data/code-insiders.log
            ci-user-data/xvfb-errors.log
            ci-user-data/process*.log
            **/*.log
      # - name: Publish Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v2
      #   if: always()
      #   with:
      #     files: |
      #       aitest/*/target/*-reports/*.xml
      #       !aitest/*/target/*-reports/failsafe-summary.xml
      #     action_fail: true
