name: Playwright Tests - openvscode-server
on:
  push:
  schedule:
    - cron: '21 21 * * *'
permissions: {}
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      IVY_JAVA_HOME: $JAVA_HOME
      CI: true
      RUN_IN_BROWSER: true
      OPEN_VSCODE_VERSION: v1.103.1
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          pnpm run update:axonivy:next
          pnpm install --no-frozen-lockfile
          pnpm run build:production
          pnpx playwright install --with-deps chromium
          pnpm run engine:download https://dev.axonivy.com/permalink/dev/axonivy-engine.zip
          rm -r extension/AxonIvyEngine/system/demo-applications
          wget -O openvsc.tar.gz https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-$OPEN_VSCODE_VERSION/openvscode-server-$OPEN_VSCODE_VERSION-linux-x64.tar.gz
          tar -xzf openvsc.tar.gz --strip-components=1 --one-top-level=openvsc
          cp -r extension/. openvsc/extensions/extension
          nohup openvsc/bin/openvscode-server --host 0.0.0.0 --without-connection-token --disable-workspace-trust &
          extension/AxonIvyEngine/bin/AxonIvyEngine startdaemon

      - name: Run Playwright tests
        run: pnpm run test:playwright:browser

      - name: Upload test results
        uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: |
            playwright/test-results
          retention-days: 10
